version: "3.9"

services: 
  api:
    container_name: api
    image: api_express
    build: .
    ports:
      - 8080:8080
    environment:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB"]
      interval: 10s
      timeout: 5s
      retries: 5
